# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: FlickerServices/UserService/Dockerfile
    ports:
      - 5098:5098
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
